# Generated by Django 5.1.7 on 2025-04-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0002_alter_submission_score"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="options",
        ),
        migrations.AddField(
            model_name="question",
            name="option_a",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="option_b",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="option_c",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="option_d",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="correct_answer",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")], max_length=1
            ),
        ),
    ]
