# Generated by Django 5.1.7 on 2025-04-02 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0003_remove_question_options_question_option_a_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="exam",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="exams.exam",
            ),
        ),
    ]
