# Generated by Django 5.1.7 on 2025-04-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0004_alter_question_exam"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="correct_answers",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="submission",
            name="percentage",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="submission",
            name="time_taken",
            field=models.IntegerField(default=0, help_text="Time taken in minutes"),
        ),
        migrations.AddField(
            model_name="submission",
            name="total_questions",
            field=models.IntegerField(default=0),
        ),
    ]
