# Generated by Django 5.1.7 on 2025-04-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0005_submission_correct_answers_submission_percentage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="exam_type",
            field=models.CharField(
                choices=[("APTITUDE", "Aptitude Exam"), ("CODING", "Coding Exam")],
                default="MCQ",
                max_length=10,
            ),
        ),
    ]
