# Generated by Django 5.1.7 on 2025-04-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0006_exam_exam_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="correct_output",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="test_cases",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="correct_answer",
            field=models.CharField(
                blank=True,
                choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="option_a",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="option_b",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="option_c",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="option_d",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
