# Generated by Django 5.1.7 on 2025-04-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0007_question_correct_output_question_test_cases_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="exam_type",
            field=models.CharField(
                choices=[("APTITUDE", "Aptitude Exam"), ("CODING", "Coding Exam")],
                default="APTITUDE",
                max_length=10,
            ),
        ),
    ]
