# Generated by Django 5.1.7 on 2025-04-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0008_alter_exam_exam_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="correct_output",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Expected outputs for the test cases",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="test_cases",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of test cases for coding questions",
            ),
        ),
    ]
